// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // ← changed from throw to return
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ← New web config added
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdGS3fMbLnElKYGi3rO_2zeH_vlAPCuyQ',
    appId: '1:910193430774:web:69eb4a15e3970632861cd7',
    messagingSenderId: '910193430774',
    projectId: 'manifest-emblem-451812-h1',
    storageBucket: 'manifest-emblem-451812-h1.firebasestorage.app',
    authDomain: 'manifest-emblem-451812-h1.firebaseapp.com',
    measurementId: 'G-507PVY7XEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxJH9vcmSQhg2YLDgUFxk1jpUicAXBc-E',
    appId: '1:910193430774:android:9b4a6f11bc9473b1861cd7',
    messagingSenderId: '910193430774',
    projectId: 'manifest-emblem-451812-h1',
    storageBucket: 'manifest-emblem-451812-h1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADSYUZhlKNTiM-dkYFQKa5gDjIwwQMmxs',
    appId: '1:910193430774:ios:06f849470f9ab573861cd7',
    messagingSenderId: '910193430774',
    projectId: 'manifest-emblem-451812-h1',
    storageBucket: 'manifest-emblem-451812-h1.firebasestorage.app',
    iosBundleId: 'com.example.shop',
  );
}